version: '3'

services:
  redis:
    image: redis:latest
    ports:
    - 6378:6379
  db:
    image: mariadb:latest
    environment:
      - MYSQL_USER=parham
      - MYSQL_PASSWORD=parham
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root
    ports:
    - 3305:3306